version: "3.7"

services:
  juice:
    image: bkimminich/juice-shop
    container_name: juiceshop
    depends_on:
      - traefik
      - fluentd

  traefik:
    image:  traefik:latest
    container_name: "traefik"
    command:
      - --api.dashboard=true
      - --accesslog
      - --accesslog.format=json
      - --accesslog.filepath=/var/log/access.log
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    depends_on:
      - fluentd
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "traefik:/var/log/"

  fluentd:
    build: ./fluentd
    container_name: fluentd
    depends_on:
      - openobserve
    volumes:
      - "./fluentd/conf:/fluentd/etc"
      - "traefik:/var/log/traefik/"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    environment:
      OO_USERNAME: "${OO_USERNAME:-user@supertest.com}"
      OO_PASSWORD: "${OO_PASSWORD:-12345678}"
      OO_HOST: "${OO_HOST:-http://openobserve:5080}"
  
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    container_name: openobserve
    ports:
      - 5080:5080
    volumes:
      - openobserve:/data
    environment:
      ZO_DATA_DIR: /data
      ZO_ROOT_USER_EMAIL: "${OO_USERNAME:-user@supertest.com}"
      ZO_ROOT_USER_PASSWORD: "${OO_PASSWORD:-12345678}"

volumes:
  traefik:
  openobserve: