version: "3.7"

services:
  juice:
    image: bkimminich/juice-shop
    container_name: juice-shop
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.juice.rule=Host(`juice.localhost`)"
      - "traefik.http.routers.juice.entrypoints=web"
      - "traefik.http.services.my-service.loadbalancer.server.port=3000"

  traefik:
    image: "traefik:v2.5"
    container_name: "traefik"
    command:
      - --api.dashboard=true
      - --accesslog
      - --accesslog.format=json
      #- --accesslog.filepath=/data/access.log
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    links:
      - "fluentd"
    logging:
      driver: fluentd
      options:
        tag: docker.traefik.{{.ID}}

  fluentd:
    build: ./fluentd
    container_name: fluentd
    volumes:
      - "./fluentd/conf/fluent.conf:/fluentd/etc/fluent.conf"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    environment:
      HUMIO_TOKEN: ${HUMIO_TOKEN}
      HUMIO_URL: ${HUMIO_URL}